site_name: Pyth0n C0URSE

edit_uri: edit/master/docs/
repo_url: https://github.com/FSteak/pythoncoursemkdocs/
repo_name: FSteak/pythoncoursemkdocs
site_url: https://fsteak.github.io/pythoncoursemkdocs/
theme:
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - toc.follow
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
plugins:
  - social:
      enabled: true
      cards: true
  - glightbox
  - search:
      enabled: true
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      enabled: true
      repository: FSteak/pythoncoursemkdocs
      branch: master
  - git-authors:
      enabled: true
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Uzbek
      link: https://fsteak.github.io/pythoncoursemkdocsuz
      lang: uz
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ITProggerUZ
      name: My Github Profile
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      anchorlink: true
      permalink: true
  - attr_list
  - md_in_html
  - tables
copyright: Copyright &copy; 2024 FSteak